# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI/CD

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 
          - 10.x

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Login to cloudfoundry
      uses: mlucascardoso/cf-cli-action@master
      with:
        args: login -a https://api.cf.us10.hana.ondemand.com -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }}
    - name: Test deploy command
      uses: mlucascardoso/cf-cli-action@master
      with:
        args: deploy -h